In [1]:
import pandas as pd
import numpy as np
import math

In [3]:
Ratings=pd.read_csv("C:/Users/tomar/OneDrive/Desktop/Recommender system/ratings.csv",encoding="ISO-8859-1")
Movies=pd.read_csv("C:/Users/tomar/OneDrive/Desktop/Recommender system/movies.csv",encoding="ISO-8859-1")
Tags=pd.read_csv("C:/Users/tomar/OneDrive/Desktop/Recommender system/tags.csv",encoding="ISO-8859-1")

In [18]:
a=Ratings[Ratings['userId']==320]
a[a['movieId']==260]

     userId  movieId  rating   timestamp
108     320      260     4.5  1145964264

In [4]:
TF= Tags.groupby(['movieId','tag'], as_index = False, sort = False).count().rename(columns = {'userId': 'tag_count_TF'})[['movieId','tag','tag_count_TF']]

In [5]:
Tag_distinct = Tags[['tag','movieId']].drop_duplicates()
DF =Tag_distinct.groupby(['tag'], as_index = False, sort = False).count().rename(columns = {'movieId': 'tag_count_DF'})[['tag','tag_count_DF']]
a=math.log10(len(np.unique(Tags['movieId'])))
DF['IDF']=a-np.log10(DF['tag_count_DF'])
TF = pd.merge(TF,DF,on = 'tag', how = 'left', sort = False)
TF['TF-IDF']=TF['tag_count_TF']*TF['IDF']

In [6]:
Vect_len=TF[['movieId','TF-IDF']]
Vect_len['TF-IDF-Sq']=Vect_len['TF-IDF']**2
Vect_len =Vect_len.groupby(['movieId'], as_index = False, sort = False).sum().rename(columns = {'TF-IDF-Sq': 'TF-IDF-Sq-sum'})[['movieId','TF-IDF-Sq-sum']]
Vect_len['vect_len'] = np.sqrt(Vect_len[['TF-IDF-Sq-sum']].sum(axis=1))
TF = pd.merge(TF,Vect_len,on = 'movieId', how = 'left', sort = False)
TF['TAG_WT']=TF['TF-IDF']/TF['vect_len']

C:\Users\tomar\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [20]:
Ratings_filter=Ratings[Ratings['rating']>=3.5]
distinct_users=np.unique(Ratings['userId'])
user_tag_pref=pd.DataFrame()
i=1

#enter user ID for analysis
userID = 320

user_index = distinct_users.tolist().index(userID)

for user in distinct_users[user_index:user_index+1]:
    
    if i%30==0:
        print ("user: ", i , "out of: ", len(distinct_users))
            
    user_data=  Ratings_filter[Ratings_filter['userId']==user]
    user_data = pd.merge(TF,user_data,on = 'movieId', how = 'inner', sort = False)
    user_data1 = user_data.groupby(['tag'], as_index = False, sort = False).sum().rename(columns = {'TAG_WT': 'tag_pref'})[['tag','tag_pref']]
    user_data1['user']=user
    user_tag_pref = user_tag_pref.append(user_data1, ignore_index=True)
    i=i+1

In [24]:
distinct_users=np.unique(Ratings_filter['userId'])
tag_merge_all=pd.DataFrame()

i=1

#enter user ID for analysis
userID = 320

user_index = distinct_users.tolist().index(userID)

for user in distinct_users[user_index:user_index+1]:

    
    user_tag_pref_all=  user_tag_pref[user_tag_pref['user']==user]
    distinct_movies = np.unique(TF['movieId'])
    j=1
    for movie in distinct_movies:
        
        if j%300==0:
            
            print ("movie: ", j , "out of: ", len(distinct_movies) , "with user: ", i , "out of: ", len(distinct_users))
        
        TF_Movie=  TF[TF['movieId']==movie]
        tag_merge = pd.merge(TF_Movie,user_tag_pref_all,on = 'tag', how = 'left', sort = False)
        tag_merge['tag_pref']=tag_merge['tag_pref'].fillna(0)
        tag_merge['tag_value']=tag_merge['TAG_WT']*tag_merge['tag_pref']
        
        TAG_WT_val=np.sqrt(np.sum(np.square(tag_merge['TAG_WT']), axis=0))
        tag_pref_val=np.sqrt(np.sum(np.square(user_tag_pref_all['tag_pref']), axis=0))
        
        tag_merge_final = tag_merge.groupby(['user','movieId'])[['tag_value']].sum().rename(columns = {'tag_value': 'Rating'}).reset_index()
        
        tag_merge_final['Rating']=tag_merge_final['Rating']/(TAG_WT_val*tag_pref_val)
        
        tag_merge_all = tag_merge_all.append(tag_merge_final, ignore_index=True)
        j=j+1
    i=i+1
tag_merge_all = tag_merge_all.sort_values(['user','Rating'], ascending=False)

# Removing movies already rated by user

movies_rated = Ratings[Ratings['userId']==userID]['movieId']
tag_merge_all = tag_merge_all[~tag_merge_all['movieId'].isin(movies_rated)]

movie:  300 out of:  2495 with user:  1 out of:  862
movie:  600 out of:  2495 with user:  1 out of:  862
movie:  900 out of:  2495 with user:  1 out of:  862
movie:  1200 out of:  2495 with user:  1 out of:  862
movie:  1500 out of:  2495 with user:  1 out of:  862
movie:  1800 out of:  2495 with user:  1 out of:  862
movie:  2100 out of:  2495 with user:  1 out of:  862
movie:  2400 out of:  2495 with user:  1 out of:  862

In [25]:
tag_merge_all

       user  movieId    Rating
29    320.0     32.0  0.349188
814   320.0   1748.0  0.306611
560   320.0   1206.0  0.297872
2200  320.0  48394.0  0.288340
554   320.0   1199.0  0.287614
2116  320.0  32587.0  0.287348
621   320.0   1270.0  0.283335
503   320.0   1089.0  0.278155
564   320.0   1210.0  0.276866
1987  320.0   7147.0  0.264006
1990  320.0   7153.0  0.263294
1306  320.0   2997.0  0.255072
1959  320.0   6874.0  0.249789
2320  320.0  68157.0  0.248852
2204  320.0  48780.0  0.245099
2293  320.0  60684.0  0.235090
424   320.0    924.0  0.229968
27    320.0     29.0  0.226918
316   320.0    589.0  0.218728
2074  320.0   8950.0  0.218560
2350  320.0  79132.0  0.214290
182   320.0    318.0  0.214233
333   320.0    628.0  0.213147
2275  320.0  57669.0  0.212472
2196  320.0  48043.0  0.209124
2396  320.0  97752.0  0.208919
2130  320.0  34405.0  0.207178
180   320.0    316.0  0.206741
1748  320.0   4873.0  0.206153
1821  320.0   5378.0  0.203087
...     ...      ...       ...
2033  320.0   8169.0  0.001301
2068  320.0   8907.0  0.001287
1796  320.0   5135.0  0.001286
181   320.0    317.0  0.001212
1379  320.0   3189.0  0.001140
844   320.0   1885.0  0.001120
1515  320.0   3675.0  0.001079
403   320.0    901.0  0.001072
1689  320.0   4368.0  0.001067
203   320.0    355.0  0.001064
1889  320.0   6059.0  0.001016
159   320.0    276.0  0.001012
759   320.0   1603.0  0.000959
1612  320.0   3999.0  0.000944
1030  320.0   2296.0  0.000909
1879  320.0   5970.0  0.000903
24    320.0     26.0  0.000844
275   320.0    507.0  0.000839
837   320.0   1862.0  0.000818
1208  320.0   2724.0  0.000761
255   320.0    464.0  0.000741
550   320.0   1194.0  0.000679
459   320.0   1010.0  0.000650
852   320.0   1911.0  0.000650
1251  320.0   2846.0  0.000641
1192  320.0   2694.0  0.000605
1706  320.0   4499.0  0.000582
224   320.0    381.0  0.000561
71    320.0    104.0  0.000457
527   320.0   1132.0  0.000317

[2353 rows x 3 columns]

In [63]:
distinct_users=np.unique(Ratings['userId'])
user_tag_pref=pd.DataFrame()
i=1

#enter user ID for analysis
userID = 320

user_index = distinct_users.tolist().index(userID)

for user in distinct_users[user_index:user_index+1]:    
    if i%30==0:
        print ("user: ", i , "out of: ", len(distinct_users))
            
    user_data=  Ratings[Ratings['userId']==user]
    user_data['weight']=user_data["rating"]-user_data["rating"].mean()
    user_data1 = pd.merge(TF,user_data,on = 'movieId', how = 'inner', sort = False)
    user_data1['TAG_WT_WTD'] = user_data1['TAG_WT']*user_data1['weight']
    user_data2 = user_data1.groupby(['tag'], as_index = False, sort = False).sum().rename(columns = {'TAG_WT_WTD': 'tag_pref'})[['tag','tag_pref']]
    user_data2['user']=user
    user_tag_pref = user_tag_pref.append(user_data2, ignore_index=True)
    i=i+1

C:\Users\tomar\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [64]:
distinct_users=np.unique(Ratings_filter['userId'])
tag_merge_all=pd.DataFrame()

i=1

#enter user ID for analysis
userID = 320

user_index = distinct_users.tolist().index(userID)

for user in distinct_users[user_index:user_index+1]:

    
    user_tag_pref_all=  user_tag_pref[user_tag_pref['user']==user]
    distinct_movies = np.unique(TF['movieId'])
    j=1
    for movie in distinct_movies:
        
        if j%300==0:
            
            print ("movie: ", j , "out of: ", len(distinct_movies) , "with user: ", i , "out of: ", len(distinct_users))
        
        TF_Movie=  TF[TF['movieId']==movie]
        tag_merge = pd.merge(TF_Movie,user_tag_pref_all,on = 'tag', how = 'left', sort = False)
        tag_merge['tag_pref']=tag_merge['tag_pref'].fillna(0)
        tag_merge['tag_value']=tag_merge['TAG_WT']*tag_merge['tag_pref']
        
        TAG_WT_val=np.sqrt(np.sum(np.square(tag_merge['TAG_WT']), axis=0))
        tag_pref_val=np.sqrt(np.sum(np.square(user_tag_pref_all['tag_pref']), axis=0))
        
        tag_merge_final = tag_merge.groupby(['user','movieId'])[['tag_value']].sum().rename(columns = {'tag_value': 'Rating'}).reset_index()
        
        tag_merge_final['Rating']=tag_merge_final['Rating']/(TAG_WT_val*tag_pref_val)
        
        tag_merge_all = tag_merge_all.append(tag_merge_final, ignore_index=True)
        j=j+1
    i=i+1
tag_merge_all = tag_merge_all.sort_values(['user','Rating'], ascending=False)

# Removing movies already rated by user

movies_rated = Ratings[Ratings['userId']==userID]['movieId']
tag_merge_all = tag_merge_all[~tag_merge_all['movieId'].isin(movies_rated)]

movie:  300 out of:  2495 with user:  1 out of:  862
movie:  600 out of:  2495 with user:  1 out of:  862
movie:  900 out of:  2495 with user:  1 out of:  862
movie:  1200 out of:  2495 with user:  1 out of:  862
movie:  1500 out of:  2495 with user:  1 out of:  862
movie:  1800 out of:  2495 with user:  1 out of:  862
movie:  2100 out of:  2495 with user:  1 out of:  862
movie:  2400 out of:  2495 with user:  1 out of:  862

In [65]:
tag_merge_all

       user  movieId    Rating
2216  320.0  48394.0  0.203681
2006  320.0   7153.0  0.184239
571   320.0   1210.0  0.178088
337   320.0    628.0  0.177350
1316  320.0   2997.0  0.175898
510   320.0   1089.0  0.165156
2003  320.0   7147.0  0.161338
2132  320.0  32587.0  0.160441
2220  320.0  48780.0  0.159790
561   320.0   1199.0  0.154699
1157  320.0   2542.0  0.154045
183   320.0    318.0  0.153414
567   320.0   1206.0  0.153094
1975  320.0   6874.0  0.152299
2412  320.0  97752.0  0.152263
2291  320.0  57669.0  0.151069
1969  320.0   6807.0  0.150513
833   320.0   1799.0  0.147724
2136  320.0  33493.0  0.142367
29    320.0     32.0  0.141658
374   320.0    778.0  0.140863
1763  320.0   4873.0  0.140782
2336  320.0  68157.0  0.138797
822   320.0   1748.0  0.138041
606   320.0   1248.0  0.135683
27    320.0     29.0  0.134516
1836  320.0   5378.0  0.129001
1751  320.0   4754.0  0.128198
1150  320.0   2529.0  0.126029
777   320.0   1625.0  0.124947
...     ...      ...       ...
910   320.0   2001.0 -0.054452
2007  320.0   7154.0 -0.055947
2289  320.0  57368.0 -0.055998
366   320.0    743.0 -0.056076
530   320.0   1128.0 -0.057353
1719  320.0   4487.0 -0.057929
368   320.0    748.0 -0.057941
1194  320.0   2683.0 -0.058350
216   320.0    368.0 -0.060192
1422  320.0   3269.0 -0.060331
1180  320.0   2633.0 -0.060659
1733  320.0   4639.0 -0.060884
911   320.0   2002.0 -0.061288
1583  320.0   3841.0 -0.061835
1543  320.0   3705.0 -0.063663
1558  320.0   3753.0 -0.063924
2125  320.0  30825.0 -0.064960
1684  320.0   4270.0 -0.065277
271   320.0    491.0 -0.065368
1690  320.0   4310.0 -0.065452
2353  320.0  72378.0 -0.065825
1238  320.0   2770.0 -0.067056
2313  320.0  61132.0 -0.068148
521   320.0   1101.0 -0.069960
2141  320.0  34048.0 -0.070260
2402  320.0  91630.0 -0.071626
1412  320.0   3259.0 -0.072350
1854  320.0   5502.0 -0.072453
2012  320.0   7163.0 -0.077141
1249  320.0   2802.0 -0.091720

[2369 rows x 3 columns]